### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by jpeg729** [Pomax/github-weblog#19]
If I understand this right, the entire blog is hidden behind index.html which uses javascript to show content. Thus a robot that doesn't run javascript won't see anything.

Is that an issue? Does Google manage to reference your blog anyway? My guess would be yes, but you might get slightly downranked because of the javascript dependancy.

Could the code be altered to write html files for each post and update index.html?

**Comment by Pomax** [comment]
It could be, but that would be completely counter to the whole point of writing pure markdown.

There is an RSS feed that can be used for indexing purposes, and google/yahoo these days do JS evaluation when indexing so the lack of initial content does not seem to be a problem. If you're worried about SEO, you're probably already running a highly successful blog and this package is probably too simplistic for your purposes (no stats to tell you what parts are performing how well so you can tweak for optimal delivery. It's been written as "just a blog" rather than as full blown publication platform)

**Comment by jpeg729** [comment]
Ok, so I did some testing.
I took a couple of sentence fragments from your articles and googled them. Each time google came back with a link to the index page http://pomax.github.io/ rather than a link to a more specific page. While that works, it will be confusing to users who will have to scroll down before seeing the content they wanted and might even not see it until they click load more.

I would suggest adding metadata to the articles as per the examples on this page http://schema.org/Article, though maybe using the properties on http://schema.org/BlogPosting which doesn't have examples.

On both pages the last property listed is the url of the item. That should help google understand the proper way to link to an article.

**Comment by Pomax** [comment]
there are no "specific pages", though. this setup only has one page, with fragment IDs for each article. "individual articles" are still just the main page, with all the other articles set to "invisible". If you consider being findable through search engines as important as just maintaining a simple weblog, this package is not the package for you =)

**Comment by jpeg729** [comment]
I'm guessing that if there was a little metadata sprinkled around, and each article was marked up with an url with a hashtag, then maybe google would show urls with hastags and searchers would get shown the right article. That might be all it would take.

In fact, it might be enough just to mark the surrounding div as being an article.

In any case I've got my eye on Riot https://muut.com/riotjs/ one of react's "younger brothers", and I've half a mind to try porting it or writing something similar.

**Comment by Pomax** [comment]
that looks interesting. If you want to file a new issue for adding schema metadata for individual article views, I can see about trying to work that in when I have some time.
